"""empty message

Revision ID: 70a8a634b277
Revises: 
Create Date: 2017-02-28 12:32:22.682466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a8a634b277'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('review', sa.String(length=350), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('facebook', sa.Boolean(), nullable=True),
    sa.Column('twitter', sa.Boolean(), nullable=True),
    sa.Column('linkedin', sa.Boolean(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('reviewed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews_product',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('reviews_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['reviews_id'], ['reviews.id'], )
    )
    op.drop_table('sqlite_stat1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_stat1',
    sa.Column('tbl', sa.NullType(), nullable=True),
    sa.Column('idx', sa.NullType(), nullable=True),
    sa.Column('stat', sa.NullType(), nullable=True)
    )
    op.drop_table('reviews_product')
    op.drop_table('reviews')
    op.drop_table('product')
    # ### end Alembic commands ###
