// import angular modules
import angular from 'angular';
import 'angular-ui-router';
import 'angular-messages';
// Import our app config files
import constants from './config/app.constants';
import appConfig from './config/app.config';
import appRun from './config/app.run';
// Import our templates file (generated by Gulp)
import './config/app.templates';
// Import our app functionaity
import './layout';
import './components';
import './services';
import './reviews';
import './directives';

// Create and bootstrap application
const requires = [
  'ui.router',
  'ngMessages',
  'templates',
  'app.layout',
  'app.components',
  'app.services',
  'app.reviews',
  'app.directives'
];

// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
  strictDi: true
});
